version: "3.8"
services:
  web:
    build: .
    ports:
      - "80:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - DATA_DIR=/app/data
      - MODEL_DIR=/app/models
      - LOG_DIR=/app/logs
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - ./my_modules:/app/my_modules
      - ./app.py:/app/app.py
      - ./.env:/app/.env
      - ./tests:/app/tests
      - ./logs:/app/logs
    hostname: web
    domainname: harmoni-ai.local
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  test:
    build: .
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=testing
      - DATA_DIR=/app/data
      - MODEL_DIR=/app/models
      - LOG_DIR=/app/logs
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - ./my_modules:/app/my_modules
      - ./app.py:/app/app.py
      - ./.env:/app/.env
      - ./tests:/app/tests
      - ./logs:/app/logs
    command: pytest -v --cov=app --cov=my_modules tests/
