version: "3.8"

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - DATA_DIR=/app/data
      - MODEL_DIR=/app/models
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - ./templates:/app/templates
      - ./static:/app/static
      - ./my_modules:/app/my_modules
      - ./app.py:/app/app.py
      - ./.env:/app/.env
